@startuml
title 抽奖活动工厂模式实现流程

actor 客户端
participant "抽奖服务" as LotteryService
participant "商品工厂" as StoreFactory
participant "优惠券" as CouponService
participant "实物商品" as GoodsService
participant "爱奇艺会员卡" as IQiYiCardService

客户端 -> LotteryService: 抽奖
LotteryService -> LotteryService: 抽奖算法抽奖\n获得抽奖结果中的奖品类型
LotteryService -> StoreFactory: 根据奖品类型获取对应的服务
alt prize_type = "优惠券"
   StoreFactory -> LotteryService: 优惠券类型\n返回优惠券服务
   LotteryService -> CouponService: 调用优惠券服务
else prize_type = "实物商品"
   StoreFactory -> LotteryService: 实物商品类型\n返回实物商品服务
   LotteryService -> GoodsService: 调用实物商品服务
else prize_type = "爱奇艺会员卡"
  StoreFactory -> LotteryService: 爱奇艺会员卡类型\n返回爱奇艺会员卡服务
  LotteryService -> IQiYiCardService: 调用爱奇艺会员卡服务
else "未知类型"
  StoreFactory -> StoreFactory: 抛出错误
end

LotteryService -> 客户端: 响应结果
@enduml